/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packagePrincipal.vistaAHistorialClinico;

/**
 *
 * @author Wjose
 */
public class FrameAyuda extends javax.swing.JFrame {

    /**
     * Creates new form FrameAyuda
     */
    public FrameAyuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _panel = new javax.swing.JPanel();
        _labelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _panel.setBackground(new java.awt.Color(38, 166, 154));
        _panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _labelLogo.setFont(new java.awt.Font("Metropolis Black", 1, 18)); // NOI18N
        _labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        _labelLogo.setText("OBSERVACIONES IMPORTANTES");
        _panel.add(_labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("EN ESTE APARTADO PODRÁS REGISTRAR EL HISTROIAL MÉDICO DEL PACIENTE \nASOCIADO POR MEDIO DE UNA CÉDULA.\n\nCOSAS IMPORTANTES :\n\n1.SI LAS CASILLAS ESTÁN EN ROJO SIGNIFICA QUE ESTÁN VACIÍAS, POR ENDE TIENES \nQUE LLENARLAS PARA PODER REGISTRAR EL HISTORIAL DE FORMA EXITOSA.\n\n2. EN LA CASILLA DE RAZÓN DE CONSULTA PREFERIBLEMENTE COLOCA ENTRE \nCOMILLAS LA RAZÓN EN UN TEXTO CORTO Y CONCISO EJEMPLO (\"ME DUELE LA MUELA\").\n\n3. CUALQUIER OTRA PREGUNTA CONTACTE AL PROGRAMADOR ENCARGADO.");
        jScrollPane1.setViewportView(jTextArea1);

        _panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 740, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(780, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAyuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel _labelLogo;
    javax.swing.JPanel _panel;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
