/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packagePrincipal.vistaMDatosmedico;

/**
 *
 * @author Wjose
 */
public class FrameAyuda extends javax.swing.JFrame {

    /**
     * Creates new form FrameAyuda
     */
    public FrameAyuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _panel.setBackground(new java.awt.Color(38, 166, 154));
        _panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Metropolis Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OBSERVACIONES IMPORTANTES");
        _panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("SI ESTÁS EN EL APARTADO DE REGISTRAR UN MÉDICO PODRÁS AGREGAR UN MÉDICO \nPERTENECIENTE A TU INVENTARIO DE MÉDICOS AL IGUAL QUE EN EL APARTADO DE MODIFICAR\nDATOS DEL MÉDICO PODRÁS MODIFICAR ESTE INVENTARIO PERTENECIENTE A TU CLÍNICA ODONTOLÓGICA.\n\n\nCOSAS IMPOTANTES:\n\n1. LAS IMÁGENES(FOTOS) TIENEN QUE SER DE 150*150 PÍXELES NI MÁS NI MENOS, PARA EDITAR\nDICHAS FOTOS AL ESTÁNDAR PEDIDO PUEDE USAR EL EDITOR DE PAINT EN WINDOWS\nO CUALQUIER OTRO EDITOR.\n\n2. LAS IMÁGENES(FOTOS) QUE SERÁN CARGADAS AL REGISTRO TIENEN QUE TENER COMO EXTENSIÓN \n.png o .jpg OBLIGATORIAMENTE.\n\n3. LOS CÓDIGOS TELEFÓNICOS PERMITITDOS SON (+59399 Y +59398) Y \nTAMBIÉN ESTÁ EL CASO DE QUE EL NÚMERO NO SEA CON CÓDIGO EN ESTE CASO USAMOS (099 Ó 098).\n\n4. EL ESTÁNDAR DE LAS CÉDULAS ES (LOS DOS PRIMEROS DÍGITOS SON EL CÓDIGO DE PROVINCIA, \nLOS OTROS 7 SON DÍGITOS Y EL DÉCIMO ES EL CÓDIGO VERIFICADOR).\n\n5. CUALQUIER OTRA PREGUNTA CONTACTE AL PROGRAMADOR ENCARGADO.\n");
        jScrollPane1.setViewportView(jTextArea1);

        _panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(780, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAyuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel _panel;
    javax.swing.JLabel jLabel1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
